from django.urls import path
from .views import (
    homeView,
    getBlog,
    addContent,
    loginView,
    register,
    forgotPassword,
    getAutomation,
    addUnit,
    edit_unit,
    submitContentView,
    cerete_blog_lesson,
    lesson_detail,
    lesson_list,
    unit_detail,
    unit_list,
    create_unit,
    create_lesson,
    edit_lesson,
    delete_lesson,
)

urlpatterns = [
    path('', homeView, name='home'),
    path('blog', getBlog, name='blog'),
    path('add_unit', addUnit, name='addUnit'),
    path('addContent', addContent, name='addContent'),  # Keep this one
    path('login', loginView, name='login'),
    path('register', register, name='register'),
    path('forget', forgotPassword, name='forgotPassword'),
    path('automation', getAutomation, name='automation'),
    path('create_lesson/<int:unit_id>/', create_lesson, name='create_lesson'),
    path('edit_lesson/<int:unit_id>/<int:lesson_id>/', edit_lesson, name='edit_lesson'),
    path('delete_lesson/<int:unit_id>/<int:lesson_id>', delete_lesson, name='delete_lesson'),
    path('edit_unit/<int:id>/', edit_unit, name='edit_unit'),
    path('submit_content', submitContentView, name='submitContent'),
    path('create_blog',cerete_blog_lesson,name='create_blog'),
    path('lessons/', lesson_list, name='lesson_list'),
    path('lessons/<int:unit_id>/<int:lesson_id>/', lesson_detail, name='lesson_detail'),
    path('create_unit',create_unit,name='create_unit'),
    path('units/', unit_list, name='unit_list'),
    path('units/<int:unit_id>/', unit_detail, name='unit_detail'), 
]
