# Generated by Django 4.1.7 on 2023-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryRegister', '0003_rename_descripttion_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
