# Generated by Django 4.1.7 on 2023-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
