# Generated by Django 4.2.11 on 2024-04-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_customuser_user'),
    ]

    operations = [
    ]
