# Generated by Django 4.1.7 on 2023-03-18 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_review_created_review_updated_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
